### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Embedded-Systems-Guide/interview-questions#2]
Add questions on memory management and links to its answers.

**Comment by carvalheirafc** [comment]
Hello Mr Prajapati, what types of memory management questions do you prefer ?
Could you Sir, be more specific about the context ?
I Just want to help the community.

**Comment by mehul-m-prajapati** [comment]
Hello,

I don't have a specific idea on context. You can add questions as per your wish.

**Comment by carvalheirafc** [comment]
Okay Mr. Prajapati, I will do some research about this topic(Memory Management) on this next couple days.
And thanks for the patience. This is my first try helping the git community.
